apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: goapihaha
spec:
  host: goapi.default.svc.cluster.local
  subsets:
    - name: v1
      labels:
        version: showv1
    - name: v2
      labels:
        version: showv2

---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: goapixixi
spec:
  host: goapisec.default.svc.cluster.local
  subsets:
    - name: v3
      labels:
        version: showv1
    - name: v4
      labels:
        version: showv2

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: goapi-default-xixi
spec:
  hosts:
    - kube.jemper.cn
  gateways:
    - mesh
    - example-gateway
  http:
    - route:
        - destination:
            host: goapisec.default.svc.cluster.local
            subset: v3
      match:
        - uri:
            prefix: /sec
    - route:
        - destination:
            host: goapi.default.svc.cluster.local
            subset: v1
      match:
        - uri:
            prefix: /

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: example-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 443
        name: http
        protocol: HTTP
      hosts:
        - "*.jemper.cn"